import { SolarPanel, Battery, Inverter, MPPTController } from '../types/equipment';

export const VERIFIED_SOLAR_PANELS: SolarPanel[] = [
  {
    id: 'panel-cs-hiku6-400',
    manufacturer: 'Canadian Solar',
    model: 'HiKu6 CS6R-400MS',
    sourceStatus: 'DATASHEET_VERIFIED',
    datasheetName: 'Canadian_Solar_HiKu6_CS6R-MS_Datasheet_v2.pdf',
    datasheetVerified: true,
    verificationDate: '2026-03-15',
    sourceNotes: 'Official Canadian Solar manufacturer specification sheet. 108 half-cell monocrystalline PERC.',
    ratedPowerW: 400,
    voc: 37.2,
    vmp: 31.2,
    isc: 13.68,
    imp: 12.82,
    tempCoeffVoc: -0.26,
    tempCoeffIsc: 0.05,
    tempCoeffPmax: -0.34,
    maxSystemVoltageV: 1500,
    moduleEfficiencyPercent: 20.5,
    lengthMm: 1722,
    widthMm: 1134,
    weightKg: 21.3,
    warrantyYears: 12,
  },
  {
    id: 'panel-cs-hiku6-545',
    manufacturer: 'Canadian Solar',
    model: 'HiKu6 CS6W-545MS',
    sourceStatus: 'DATASHEET_VERIFIED',
    datasheetName: 'Canadian_Solar_HiKu6_CS6W-MS_545W.pdf',
    datasheetVerified: true,
    verificationDate: '2026-02-10',
    sourceNotes: '144 half-cell monocrystalline module for large residential and commercial off-grid installations.',
    ratedPowerW: 545,
    voc: 49.4,
    vmp: 41.5,
    isc: 13.92,
    imp: 13.14,
    tempCoeffVoc: -0.26,
    tempCoeffIsc: 0.05,
    tempCoeffPmax: -0.34,
    maxSystemVoltageV: 1500,
    moduleEfficiencyPercent: 21.3,
    lengthMm: 2278,
    widthMm: 1134,
    weightKg: 27.6,
    warrantyYears: 12,
  },
  {
    id: 'panel-ja-jam72s30-545',
    manufacturer: 'JA Solar',
    model: 'JAM72S30 545/MR',
    sourceStatus: 'DATASHEET_VERIFIED',
    datasheetName: 'JA_Solar_JAM72S30_530-555_MR_Global.pdf',
    datasheetVerified: true,
    verificationDate: '2026-01-20',
    sourceNotes: 'JA Solar DeepBlue 3.0 Series 11BB MBB Half-cell module.',
    ratedPowerW: 545,
    voc: 49.75,
    vmp: 41.80,
    isc: 13.93,
    imp: 13.04,
    tempCoeffVoc: -0.275,
    tempCoeffIsc: 0.045,
    tempCoeffPmax: -0.35,
    maxSystemVoltageV: 1500,
    moduleEfficiencyPercent: 21.1,
    lengthMm: 2279,
    widthMm: 1134,
    weightKg: 28.6,
    warrantyYears: 12,
  },
  {
    id: 'panel-jinko-tigerpro-550',
    manufacturer: 'Jinko Solar',
    model: 'Tiger Pro 72HC 550M',
    sourceStatus: 'DATASHEET_VERIFIED',
    datasheetName: 'Jinko_TigerPro_72HC_530-550M.pdf',
    datasheetVerified: true,
    verificationDate: '2026-03-01',
    sourceNotes: 'Multi-busbar technology with lower hot-spot degradation and positive power tolerance.',
    ratedPowerW: 550,
    voc: 49.62,
    vmp: 40.90,
    isc: 14.03,
    imp: 13.45,
    tempCoeffVoc: -0.28,
    tempCoeffIsc: 0.048,
    tempCoeffPmax: -0.35,
    maxSystemVoltageV: 1500,
    moduleEfficiencyPercent: 21.33,
    lengthMm: 2274,
    widthMm: 1134,
    weightKg: 28.0,
    warrantyYears: 12,
  },
  {
    id: 'panel-longi-himo5-545',
    manufacturer: 'LONGi',
    model: 'Hi-MO 5 LR5-72HPH-545M',
    sourceStatus: 'DATASHEET_VERIFIED',
    datasheetName: 'LONGi_HiMO5_LR5-72HPH_535-555M.pdf',
    datasheetVerified: true,
    verificationDate: '2026-02-18',
    sourceNotes: 'Gallium-doped wafer with standard M10 cell geometry.',
    ratedPowerW: 545,
    voc: 49.65,
    vmp: 41.80,
    isc: 13.92,
    imp: 13.04,
    tempCoeffVoc: -0.28,
    tempCoeffIsc: 0.05,
    tempCoeffPmax: -0.35,
    maxSystemVoltageV: 1500,
    moduleEfficiencyPercent: 21.3,
    lengthMm: 2256,
    widthMm: 1133,
    weightKg: 27.2,
    warrantyYears: 12,
  },
  {
    id: 'panel-generic-400',
    manufacturer: 'Generic Tier-1',
    model: 'Mono PERC 400W Standard',
    sourceStatus: 'PRESET',
    sourceNotes: 'Typical standard 108/120 half-cell monocrystalline module baseline.',
    ratedPowerW: 400,
    voc: 37.2,
    vmp: 31.1,
    isc: 13.80,
    imp: 12.90,
    tempCoeffVoc: -0.28,
    tempCoeffIsc: 0.05,
    tempCoeffPmax: -0.35,
    maxSystemVoltageV: 1000,
    moduleEfficiencyPercent: 20.4,
    lengthMm: 1722,
    widthMm: 1134,
    weightKg: 21.5,
    warrantyYears: 10,
  },
];

export const VERIFIED_BATTERIES: Battery[] = [
  {
    id: 'batt-pylontech-us5000',
    manufacturer: 'Pylontech',
    model: 'US5000 (48V 100Ah)',
    sourceStatus: 'DATASHEET_VERIFIED',
    datasheetName: 'Pylontech_US5000_Datasheet_2024.pdf',
    datasheetVerified: true,
    verificationDate: '2026-03-10',
    sourceNotes: 'Standard 48V (51.2V nominal) server-rack LiFePO4 battery module with integrated BMS.',
    chemistry: 'LiFePO4',
    nominalVoltageV: 51.2,
    nominalAh: 100,
    nominalKwh: 4.8,
    recommendedDodPercent: 95,
    maxContinuousChargeCurrentA: 80, // Recommended 50A, max continuous 80A
    maxContinuousDischargeCurrentA: 80, // Recommended 50A, max continuous 80A
    peakDischargeCurrentA: 100, // 101-120A 15min, 121-200A 15sec
    maxParallelUnits: 16,
    maxSeriesUnits: 1,
    communicationProtocols: ['CAN', 'RS485'],
    operatingTempMinC: 0,
    operatingTempMaxC: 50,
    cycleLife: 6000,
    warrantyYears: 10,
  },
  {
    id: 'batt-pylontech-us3000c',
    manufacturer: 'Pylontech',
    model: 'US3000C (48V 74Ah)',
    sourceStatus: 'DATASHEET_VERIFIED',
    datasheetName: 'Pylontech_US3000C_Datasheet.pdf',
    datasheetVerified: true,
    verificationDate: '2026-01-15',
    sourceNotes: 'Compact rack-mount 3.55 kWh storage module.',
    chemistry: 'LiFePO4',
    nominalVoltageV: 48.0,
    nominalAh: 74,
    nominalKwh: 3.55,
    recommendedDodPercent: 95,
    maxContinuousChargeCurrentA: 37,
    maxContinuousDischargeCurrentA: 37,
    peakDischargeCurrentA: 90,
    maxParallelUnits: 16,
    maxSeriesUnits: 1,
    communicationProtocols: ['CAN', 'RS485'],
    operatingTempMinC: 0,
    operatingTempMaxC: 50,
    cycleLife: 6000,
    warrantyYears: 10,
  },
  {
    id: 'batt-eg4-lifepower4',
    manufacturer: 'EG4',
    model: 'LifePower4 48V V2',
    sourceStatus: 'DATASHEET_VERIFIED',
    datasheetName: 'EG4_LifePower4_48V_Specification_Sheet.pdf',
    datasheetVerified: true,
    verificationDate: '2026-02-28',
    sourceNotes: '51.2V 100Ah server rack battery with dual protocol auto-addressing BMS.',
    chemistry: 'LiFePO4',
    nominalVoltageV: 51.2,
    nominalAh: 100,
    nominalKwh: 5.12,
    recommendedDodPercent: 80,
    maxContinuousChargeCurrentA: 100,
    maxContinuousDischargeCurrentA: 100,
    peakDischargeCurrentA: 150,
    maxParallelUnits: 16,
    maxSeriesUnits: 1,
    communicationProtocols: ['CAN', 'RS485'],
    operatingTempMinC: -10,
    operatingTempMaxC: 50,
    cycleLife: 7000,
    warrantyYears: 5,
  },
  {
    id: 'batt-dyness-bx51100',
    manufacturer: 'Dyness',
    model: 'BX51100 Lithium LFP',
    sourceStatus: 'DATASHEET_VERIFIED',
    datasheetName: 'Dyness_BX51100_Datasheet.pdf',
    datasheetVerified: true,
    verificationDate: '2026-01-30',
    sourceNotes: 'Modular residential energy storage with natural cooling.',
    chemistry: 'LiFePO4',
    nominalVoltageV: 51.2,
    nominalAh: 100,
    nominalKwh: 5.12,
    recommendedDodPercent: 90,
    maxContinuousChargeCurrentA: 50,
    maxContinuousDischargeCurrentA: 75,
    peakDischargeCurrentA: 100,
    maxParallelUnits: 40,
    maxSeriesUnits: 1,
    communicationProtocols: ['CAN', 'RS485'],
    operatingTempMinC: 0,
    operatingTempMaxC: 50,
    cycleLife: 6000,
    warrantyYears: 10,
  },
  {
    id: 'batt-victron-smart-25',
    manufacturer: 'Victron',
    model: 'Lithium Battery Smart 25.6V 200Ah',
    sourceStatus: 'DATASHEET_VERIFIED',
    datasheetName: 'Victron_Lithium_Battery_Smart_25.6V_Datasheet.pdf',
    datasheetVerified: true,
    verificationDate: '2026-03-05',
    sourceNotes: 'Heavy-duty marine/off-grid LFP block requiring external VE.Bus BMS.',
    chemistry: 'LiFePO4',
    nominalVoltageV: 25.6,
    nominalAh: 200,
    nominalKwh: 5.12,
    recommendedDodPercent: 80,
    maxContinuousChargeCurrentA: 100,
    maxContinuousDischargeCurrentA: 200,
    peakDischargeCurrentA: 400,
    maxParallelUnits: 5,
    maxSeriesUnits: 2, // Can be connected 2 in series for 48V
    communicationProtocols: ['VE.Bus', 'Bluetooth'],
    operatingTempMinC: -20,
    operatingTempMaxC: 50,
    cycleLife: 5000,
    warrantyYears: 5,
  },
  {
    id: 'batt-trojan-t105',
    manufacturer: 'Trojan',
    model: 'T-105 Deep-Cycle Flooded 6V',
    sourceStatus: 'PRESET',
    sourceNotes: 'Traditional lead-acid deep-cycle golf-cart/solar battery string (8 in series for 48V).',
    chemistry: 'Flooded',
    nominalVoltageV: 6.0,
    nominalAh: 225,
    nominalKwh: 1.35,
    recommendedDodPercent: 50,
    maxContinuousChargeCurrentA: 35,
    maxContinuousDischargeCurrentA: 75,
    peakDischargeCurrentA: 150,
    maxParallelUnits: 4,
    maxSeriesUnits: 8,
    communicationProtocols: [],
    operatingTempMinC: -20,
    operatingTempMaxC: 45,
    cycleLife: 1200,
    warrantyYears: 1,
  },
];

export const VERIFIED_INVERTERS: Inverter[] = [
  {
    id: 'inv-victron-multiplus2-5k',
    manufacturer: 'Victron',
    model: 'MultiPlus-II 48/5000/70-50',
    sourceStatus: 'DATASHEET_VERIFIED',
    datasheetName: 'Victron_MultiPlus-II_48-5000-70-50_Datasheet.pdf',
    datasheetVerified: true,
    verificationDate: '2026-03-12',
    sourceNotes: 'Low-frequency toroidal inverter/charger with exceptional inductive surge tolerance.',
    continuousOutputPowerKw: 4.0, // 4000W continuous at 25°C (5000VA)
    surgePowerKw: 9.0, // 9000W peak surge
    surgeDurationSec: 5,
    batteryVoltageV: 48,
    maxDcInputCurrentA: 125,
    acOutputVoltageV: 230,
    acFrequencyHz: 50,
    efficiencyPercent: 95.0,
    lowVoltageCutoffV: 37.2,
    isHybrid: false,
    parallelCapability: true,
    supportedBatteryComms: ['CAN', 'VE.Bus', 'RS485'],
    warrantyYears: 5,
  },
  {
    id: 'inv-victron-quattro-10k',
    manufacturer: 'Victron',
    model: 'Quattro 48/10000/140-100',
    sourceStatus: 'DATASHEET_VERIFIED',
    datasheetName: 'Victron_Quattro_8k_10k_15k_Datasheet.pdf',
    datasheetVerified: true,
    verificationDate: '2026-02-22',
    sourceNotes: 'Heavy industrial off-grid inverter with dual AC inputs for generator auto-start transfer.',
    continuousOutputPowerKw: 8.0, // 8000W continuous at 25°C (10000VA)
    surgePowerKw: 20.0,
    surgeDurationSec: 10,
    batteryVoltageV: 48,
    maxDcInputCurrentA: 250,
    acOutputVoltageV: 230,
    acFrequencyHz: 50,
    efficiencyPercent: 96.0,
    lowVoltageCutoffV: 38.0,
    isHybrid: false,
    parallelCapability: true,
    supportedBatteryComms: ['CAN', 'VE.Bus'],
    warrantyYears: 5,
  },
  {
    id: 'inv-deye-sun-6k',
    manufacturer: 'Deye',
    model: 'SUN-6K-SG01LP1-EU',
    sourceStatus: 'DATASHEET_VERIFIED',
    datasheetName: 'Deye_SUN-5-6K-SG01LP1-EU_Datasheet.pdf',
    datasheetVerified: true,
    verificationDate: '2026-03-14',
    sourceNotes: 'High-efficiency hybrid single-phase low-voltage inverter with dual integrated MPPTs.',
    continuousOutputPowerKw: 6.0,
    surgePowerKw: 12.0, // 2x rated power for 10s
    surgeDurationSec: 10,
    batteryVoltageV: 48, // Operating battery range 40V - 60V
    maxDcInputCurrentA: 135, // 135A max charging / discharging current
    acOutputVoltageV: 230,
    acFrequencyHz: 50,
    efficiencyPercent: 97.6,
    lowVoltageCutoffV: 40.0,
    isHybrid: true,
    maxPvInputPowerKw: 7.8,
    numberOfMppts: 2,
    maxPvVoc: 500,
    mpptVoltageRangeMinV: 125,
    mpptVoltageRangeMaxV: 425,
    maxPvCurrentPerMpptA: 13,
    maxShortCircuitCurrentA: 17,
    parallelCapability: true,
    supportedBatteryComms: ['CAN', 'RS485'],
    warrantyYears: 5,
  },
  {
    id: 'inv-deye-sun-8k',
    manufacturer: 'Deye',
    model: 'SUN-8K-SG01LP1-EU',
    sourceStatus: 'DATASHEET_VERIFIED',
    datasheetName: 'Deye_SUN-7.6-8K-SG01LP1-EU_Datasheet.pdf',
    datasheetVerified: true,
    verificationDate: '2026-03-01',
    sourceNotes: '8kW continuous single-phase hybrid inverter with 190A battery bus capability.',
    continuousOutputPowerKw: 8.0,
    surgePowerKw: 16.0,
    surgeDurationSec: 10,
    batteryVoltageV: 48,
    maxDcInputCurrentA: 190,
    acOutputVoltageV: 230,
    acFrequencyHz: 50,
    efficiencyPercent: 97.6,
    lowVoltageCutoffV: 40.0,
    isHybrid: true,
    maxPvInputPowerKw: 10.4,
    numberOfMppts: 2,
    maxPvVoc: 500,
    mpptVoltageRangeMinV: 125,
    mpptVoltageRangeMaxV: 425,
    maxPvCurrentPerMpptA: 26,
    maxShortCircuitCurrentA: 34,
    parallelCapability: true,
    supportedBatteryComms: ['CAN', 'RS485'],
    warrantyYears: 5,
  },
  {
    id: 'inv-deye-sun-12k-3p',
    manufacturer: 'Deye',
    model: 'SUN-12K-SG04LP3-EU',
    sourceStatus: 'DATASHEET_VERIFIED',
    datasheetName: 'Deye_SUN-12K-SG04LP3-EU_ThreePhase_Datasheet.pdf',
    datasheetVerified: true,
    verificationDate: '2026-02-15',
    sourceNotes: 'Three-phase 400V/230V hybrid inverter running on low-voltage 48V battery bank.',
    continuousOutputPowerKw: 12.0,
    surgePowerKw: 24.0,
    surgeDurationSec: 10,
    batteryVoltageV: 48,
    maxDcInputCurrentA: 240,
    acOutputVoltageV: 400,
    acFrequencyHz: 50,
    efficiencyPercent: 97.6,
    lowVoltageCutoffV: 40.0,
    isHybrid: true,
    maxPvInputPowerKw: 15.6,
    numberOfMppts: 2,
    maxPvVoc: 800,
    mpptVoltageRangeMinV: 200,
    mpptVoltageRangeMaxV: 650,
    maxPvCurrentPerMpptA: 26,
    maxShortCircuitCurrentA: 34,
    parallelCapability: true,
    supportedBatteryComms: ['CAN', 'RS485'],
    warrantyYears: 5,
  },
  {
    id: 'inv-growatt-spf-5000es',
    manufacturer: 'Growatt',
    model: 'SPF 5000 ES',
    sourceStatus: 'DATASHEET_VERIFIED',
    datasheetName: 'Growatt_SPF_5000_ES_Datasheet.pdf',
    datasheetVerified: true,
    verificationDate: '2026-01-25',
    sourceNotes: 'Single-phase transformerless off-grid inverter with integrated 450V MPPT.',
    continuousOutputPowerKw: 5.0,
    surgePowerKw: 10.0,
    surgeDurationSec: 5,
    batteryVoltageV: 48,
    maxDcInputCurrentA: 110,
    acOutputVoltageV: 230,
    acFrequencyHz: 50,
    efficiencyPercent: 93.0,
    lowVoltageCutoffV: 42.0,
    isHybrid: true,
    maxPvInputPowerKw: 6.0,
    numberOfMppts: 1,
    maxPvVoc: 450,
    mpptVoltageRangeMinV: 120,
    mpptVoltageRangeMaxV: 430,
    maxPvCurrentPerMpptA: 22,
    maxShortCircuitCurrentA: 27,
    parallelCapability: true,
    supportedBatteryComms: ['CAN', 'RS485'],
    warrantyYears: 2,
  },
  {
    id: 'inv-eg4-18kpv',
    manufacturer: 'EG4',
    model: '18kPV All-In-One',
    sourceStatus: 'DATASHEET_VERIFIED',
    datasheetName: 'EG4_18kPV_Spec_Sheet.pdf',
    datasheetVerified: true,
    verificationDate: '2026-02-12',
    sourceNotes: 'High-power 12kW continuous AC output hybrid inverter with split-phase 120/240V.',
    continuousOutputPowerKw: 12.0,
    surgePowerKw: 18.0,
    surgeDurationSec: 10,
    batteryVoltageV: 48,
    maxDcInputCurrentA: 250,
    acOutputVoltageV: 240,
    acFrequencyHz: 60,
    efficiencyPercent: 97.5,
    lowVoltageCutoffV: 42.0,
    isHybrid: true,
    maxPvInputPowerKw: 18.0,
    numberOfMppts: 3,
    maxPvVoc: 600,
    mpptVoltageRangeMinV: 120,
    mpptVoltageRangeMaxV: 500,
    maxPvCurrentPerMpptA: 25,
    maxShortCircuitCurrentA: 31,
    parallelCapability: true,
    supportedBatteryComms: ['CAN', 'RS485'],
    warrantyYears: 10,
  },
];

export const VERIFIED_MPPT_CONTROLLERS: MPPTController[] = [
  {
    id: 'mppt-victron-150-85',
    manufacturer: 'Victron',
    model: 'SmartSolar MPPT 150/85-Tr',
    sourceStatus: 'DATASHEET_VERIFIED',
    datasheetName: 'Victron_SmartSolar_MPPT_150-70_to_150-100_Datasheet.pdf',
    datasheetVerified: true,
    verificationDate: '2026-03-08',
    sourceNotes: 'Ultrafast MPPT with Bluetooth Smart built-in for 12/24/36/48V battery systems.',
    batteryVoltageSupport: [12, 24, 36, 48],
    maxPvVoc: 150,
    mpptVoltageMinV: 60, // Typically Vbat + 5V
    mpptVoltageMaxV: 145,
    maxPvInputCurrentA: 70,
    maxPvShortCircuitCurrentA: 70,
    maxChargingCurrentA: 85,
    maxPvPowerW_48V: 4900,
    efficiencyPercent: 98.0,
    numberOfTrackers: 1,
    warrantyYears: 5,
  },
  {
    id: 'mppt-victron-250-100',
    manufacturer: 'Victron',
    model: 'SmartSolar MPPT 250/100-Tr',
    sourceStatus: 'DATASHEET_VERIFIED',
    datasheetName: 'Victron_SmartSolar_MPPT_250-70_to_250-100_Datasheet.pdf',
    datasheetVerified: true,
    verificationDate: '2026-03-10',
    sourceNotes: 'High voltage 250V PV input allowing 5-6 panels in series for 48V battery banks.',
    batteryVoltageSupport: [12, 24, 36, 48],
    maxPvVoc: 250,
    mpptVoltageMinV: 60,
    mpptVoltageMaxV: 245,
    maxPvInputCurrentA: 70,
    maxPvShortCircuitCurrentA: 70,
    maxChargingCurrentA: 100,
    maxPvPowerW_48V: 5800,
    efficiencyPercent: 99.0,
    numberOfTrackers: 1,
    warrantyYears: 5,
  },
  {
    id: 'mppt-victron-rs-450-100',
    manufacturer: 'Victron',
    model: 'SmartSolar MPPT RS 450/100-Tr',
    sourceStatus: 'DATASHEET_VERIFIED',
    datasheetName: 'Victron_SmartSolar_MPPT_RS_450-100_Datasheet.pdf',
    datasheetVerified: true,
    verificationDate: '2026-02-20',
    sourceNotes: 'Dual isolated 450V MPPT trackers for high voltage solar arrays with 48V battery banks.',
    batteryVoltageSupport: [48],
    maxPvVoc: 450,
    mpptVoltageMinV: 120,
    mpptVoltageMaxV: 450,
    maxPvInputCurrentA: 18, // per tracker
    maxPvShortCircuitCurrentA: 20, // per tracker
    maxChargingCurrentA: 100,
    maxPvPowerW_48V: 5760,
    efficiencyPercent: 96.0,
    numberOfTrackers: 2,
    warrantyYears: 5,
  },
  {
    id: 'mppt-midnite-classic-150',
    manufacturer: 'MidNite Solar',
    model: 'Classic 150 MPPT',
    sourceStatus: 'DATASHEET_VERIFIED',
    datasheetName: 'MidNite_Solar_Classic_150_Specs.pdf',
    datasheetVerified: true,
    verificationDate: '2026-01-10',
    sourceNotes: 'Made in USA with HyperVOC cold temperature protection and Ethernet monitoring.',
    batteryVoltageSupport: [12, 24, 48, 72],
    maxPvVoc: 150,
    mpptVoltageMinV: 60,
    mpptVoltageMaxV: 140,
    maxPvInputCurrentA: 80,
    maxPvShortCircuitCurrentA: 80,
    maxChargingCurrentA: 96,
    maxPvPowerW_48V: 5600,
    efficiencyPercent: 98.0,
    numberOfTrackers: 1,
    warrantyYears: 5,
  },
];

export function getAllSolarPanels(customPanels?: SolarPanel[]): SolarPanel[] {
  return [...VERIFIED_SOLAR_PANELS, ...(customPanels || [])];
}

export function getAllBatteries(customBatteries?: Battery[]): Battery[] {
  return [...VERIFIED_BATTERIES, ...(customBatteries || [])];
}

export function getAllInverters(customInverters?: Inverter[]): Inverter[] {
  return [...VERIFIED_INVERTERS, ...(customInverters || [])];
}

export function getAllMppts(customMppts?: MPPTController[]): MPPTController[] {
  return [...VERIFIED_MPPT_CONTROLLERS, ...(customMppts || [])];
}

export function getPanelById(id?: string, customPanels?: SolarPanel[]): SolarPanel | undefined {
  if (!id) return VERIFIED_SOLAR_PANELS[0];
  return getAllSolarPanels(customPanels).find((p) => p.id === id);
}

export function getBatteryById(id?: string, customBatteries?: Battery[]): Battery | undefined {
  if (!id) return VERIFIED_BATTERIES[0];
  return getAllBatteries(customBatteries).find((b) => b.id === id);
}

export function getInverterById(id?: string, customInverters?: Inverter[]): Inverter | undefined {
  if (!id) return VERIFIED_INVERTERS[2]; // Default Deye 6kW
  return getAllInverters(customInverters).find((i) => i.id === id);
}

export function getMpptById(id?: string, customMppts?: MPPTController[]): MPPTController | undefined {
  if (!id) return VERIFIED_MPPT_CONTROLLERS[1]; // Default Victron 250/100
  return getAllMppts(customMppts).find((m) => m.id === id);
}
