import { Appliance, LocationConfig, Project } from '../types/solar';

export interface PresetApplianceItem {
  name: string;
  category: 'lighting' | 'cooling' | 'kitchen' | 'electronics' | 'water' | 'appliances' | 'other';
  defaultWatts: number;
  defaultHours: number;
  defaultDayHours: number;
  defaultNightHours: number;
  simultaneousFactor: number;
  surgeMultiplier: number;
  iconName?: string;
}

export const PRESET_APPLIANCES: PresetApplianceItem[] = [
  {
    name: 'LED Light',
    category: 'lighting',
    defaultWatts: 15,
    defaultHours: 6,
    defaultDayHours: 1,
    defaultNightHours: 5,
    simultaneousFactor: 0.8,
    surgeMultiplier: 1.0,
  },
  {
    name: 'Refrigerator',
    category: 'kitchen',
    defaultWatts: 180,
    defaultHours: 24,
    defaultDayHours: 12,
    defaultNightHours: 12,
    simultaneousFactor: 0.6,
    surgeMultiplier: 4.5,
  },
  {
    name: 'Freezer',
    category: 'kitchen',
    defaultWatts: 200,
    defaultHours: 24,
    defaultDayHours: 12,
    defaultNightHours: 12,
    simultaneousFactor: 0.6,
    surgeMultiplier: 4.5,
  },
  {
    name: 'Television',
    category: 'electronics',
    defaultWatts: 120,
    defaultHours: 6,
    defaultDayHours: 2,
    defaultNightHours: 4,
    simultaneousFactor: 0.9,
    surgeMultiplier: 1.2,
  },
  {
    name: 'Laptop',
    category: 'electronics',
    defaultWatts: 65,
    defaultHours: 8,
    defaultDayHours: 6,
    defaultNightHours: 2,
    simultaneousFactor: 0.7,
    surgeMultiplier: 1.1,
  },
  {
    name: 'Desktop Computer',
    category: 'electronics',
    defaultWatts: 250,
    defaultHours: 6,
    defaultDayHours: 4,
    defaultNightHours: 2,
    simultaneousFactor: 0.8,
    surgeMultiplier: 1.2,
  },
  {
    name: 'Wi-Fi Router',
    category: 'electronics',
    defaultWatts: 15,
    defaultHours: 24,
    defaultDayHours: 12,
    defaultNightHours: 12,
    simultaneousFactor: 1.0,
    surgeMultiplier: 1.0,
  },
  {
    name: 'Air Conditioner',
    category: 'cooling',
    defaultWatts: 1500,
    defaultHours: 8,
    defaultDayHours: 5,
    defaultNightHours: 3,
    simultaneousFactor: 0.75,
    surgeMultiplier: 3.5,
  },
  {
    name: 'Fan',
    category: 'cooling',
    defaultWatts: 50,
    defaultHours: 8,
    defaultDayHours: 3,
    defaultNightHours: 5,
    simultaneousFactor: 0.9,
    surgeMultiplier: 1.5,
  },
  {
    name: 'Ceiling Fan',
    category: 'cooling',
    defaultWatts: 65,
    defaultHours: 10,
    defaultDayHours: 4,
    defaultNightHours: 6,
    simultaneousFactor: 0.9,
    surgeMultiplier: 1.5,
  },
  {
    name: 'Coffee Machine',
    category: 'kitchen',
    defaultWatts: 1200,
    defaultHours: 0.5,
    defaultDayHours: 0.5,
    defaultNightHours: 0,
    simultaneousFactor: 0.4,
    surgeMultiplier: 1.0,
  },
  {
    name: 'Microwave',
    category: 'kitchen',
    defaultWatts: 1200,
    defaultHours: 0.5,
    defaultDayHours: 0.3,
    defaultNightHours: 0.2,
    simultaneousFactor: 0.5,
    surgeMultiplier: 1.5,
  },
  {
    name: 'Air Fryer',
    category: 'kitchen',
    defaultWatts: 1500,
    defaultHours: 0.8,
    defaultDayHours: 0.4,
    defaultNightHours: 0.4,
    simultaneousFactor: 0.5,
    surgeMultiplier: 1.0,
  },
  {
    name: 'Washing Machine',
    category: 'appliances',
    defaultWatts: 800,
    defaultHours: 1.5,
    defaultDayHours: 1.5,
    defaultNightHours: 0,
    simultaneousFactor: 0.5,
    surgeMultiplier: 2.5,
  },
  {
    name: 'Water Pump',
    category: 'water',
    defaultWatts: 750,
    defaultHours: 2.0,
    defaultDayHours: 1.5,
    defaultNightHours: 0.5,
    simultaneousFactor: 0.6,
    surgeMultiplier: 4.0,
  },
  {
    name: 'Shower Water Heater',
    category: 'water',
    defaultWatts: 2500,
    defaultHours: 1.0,
    defaultDayHours: 0.5,
    defaultNightHours: 0.5,
    simultaneousFactor: 0.4,
    surgeMultiplier: 1.0,
  },
  {
    name: 'Electric Kettle',
    category: 'kitchen',
    defaultWatts: 1800,
    defaultHours: 0.4,
    defaultDayHours: 0.3,
    defaultNightHours: 0.1,
    simultaneousFactor: 0.4,
    surgeMultiplier: 1.0,
  },
  {
    name: 'Iron',
    category: 'appliances',
    defaultWatts: 1400,
    defaultHours: 0.8,
    defaultDayHours: 0.8,
    defaultNightHours: 0,
    simultaneousFactor: 0.5,
    surgeMultiplier: 1.0,
  },
  {
    name: 'Dishwasher',
    category: 'kitchen',
    defaultWatts: 1400,
    defaultHours: 1.5,
    defaultDayHours: 1.0,
    defaultNightHours: 0.5,
    simultaneousFactor: 0.5,
    surgeMultiplier: 2.0,
  },
  {
    name: 'Security Cameras',
    category: 'electronics',
    defaultWatts: 40,
    defaultHours: 24,
    defaultDayHours: 12,
    defaultNightHours: 12,
    simultaneousFactor: 1.0,
    surgeMultiplier: 1.0,
  },
  {
    name: 'Phone Charger',
    category: 'electronics',
    defaultWatts: 20,
    defaultHours: 4,
    defaultDayHours: 2,
    defaultNightHours: 2,
    simultaneousFactor: 0.8,
    surgeMultiplier: 1.0,
  },
  {
    name: 'Other / Custom Load',
    category: 'other',
    defaultWatts: 300,
    defaultHours: 4,
    defaultDayHours: 2,
    defaultNightHours: 2,
    simultaneousFactor: 0.8,
    surgeMultiplier: 1.0,
  },
];

export const PRESET_LOCATIONS: LocationConfig[] = [
  { country: 'Senegal', city: 'Thiès', peakSunHours: 5.5, cloudyDaysBuffer: 0 },
  { country: 'Senegal', city: 'Dakar', peakSunHours: 5.4, cloudyDaysBuffer: 0 },
  { country: 'Morocco', city: 'Marrakech', peakSunHours: 5.8, cloudyDaysBuffer: 0 },
  { country: 'Mali', city: 'Bamako', peakSunHours: 5.7, cloudyDaysBuffer: 0 },
  { country: 'Kenya', city: 'Nairobi', peakSunHours: 5.6, cloudyDaysBuffer: 1 },
  { country: 'Spain', city: 'Seville', peakSunHours: 5.3, cloudyDaysBuffer: 1 },
  { country: 'USA', city: 'Boston', peakSunHours: 4.2, cloudyDaysBuffer: 2 },
  { country: 'USA', city: 'Phoenix', peakSunHours: 6.2, cloudyDaysBuffer: 0 },
];

/**
 * Initial Realistic Demo Project
 * Configured according to prompt requirement:
 * - Location: Thiès, Senegal (5.5 PSH)
 * - Daily load: approximately 24.8 kWh/day
 * - 48V System, LiFePO4 51.2V 100Ah
 * - 400W Panels
 * Yields approximately 8-10 kW solar, 30-40 kWh battery, 10-12 kW inverter.
 */
export const INITIAL_DEMO_PROJECT: Project = {
  id: 'demo-project-thies',
  name: 'Thiès Residence - Off-Grid System',
  createdAt: '2026-10-02T10:00:00.000Z',
  updatedAt: '2026-10-02T10:00:00.000Z',
  notes: 'Complete off-grid solar and energy storage engineering design for a primary villa in Thiès, Senegal.',
  appliances: [
    {
      id: 'app-1',
      name: 'Air Conditioner (1.5 HP Inverter)',
      category: 'cooling',
      quantity: 2,
      watts: 1200,
      hoursPerDay: 7,
      dayHours: 4.5,
      nightHours: 2.5,
      simultaneousFactor: 0.75,
      surgeMultiplier: 3.2,
      enabled: true,
    },
    {
      id: 'app-2',
      name: 'Refrigerator (Double Door A++)',
      category: 'kitchen',
      quantity: 1,
      watts: 160,
      hoursPerDay: 24,
      dayHours: 12,
      nightHours: 12,
      simultaneousFactor: 0.65,
      surgeMultiplier: 4.5,
      enabled: true,
    },
    {
      id: 'app-3',
      name: 'Deep Chest Freezer',
      category: 'kitchen',
      quantity: 1,
      watts: 140,
      hoursPerDay: 24,
      dayHours: 12,
      nightHours: 12,
      simultaneousFactor: 0.60,
      surgeMultiplier: 4.5,
      enabled: true,
    },
    {
      id: 'app-4',
      name: 'Submersible Water Pump (1 HP)',
      category: 'water',
      quantity: 1,
      watts: 750,
      hoursPerDay: 2.5,
      dayHours: 2.0,
      nightHours: 0.5,
      simultaneousFactor: 0.7,
      surgeMultiplier: 4.0,
      enabled: true,
    },
    {
      id: 'app-5',
      name: 'LED Lighting Fixtures',
      category: 'lighting',
      quantity: 15,
      watts: 12,
      hoursPerDay: 6,
      dayHours: 1,
      nightHours: 5,
      simultaneousFactor: 0.8,
      surgeMultiplier: 1.0,
      enabled: true,
    },
    {
      id: 'app-6',
      name: 'Smart TV (55" 4K)',
      category: 'electronics',
      quantity: 2,
      watts: 110,
      hoursPerDay: 5,
      dayHours: 1.5,
      nightHours: 3.5,
      simultaneousFactor: 0.85,
      surgeMultiplier: 1.2,
      enabled: true,
    },
    {
      id: 'app-7',
      name: 'Ceiling Fans',
      category: 'cooling',
      quantity: 4,
      watts: 60,
      hoursPerDay: 10,
      dayHours: 4,
      nightHours: 6,
      simultaneousFactor: 0.9,
      surgeMultiplier: 1.5,
      enabled: true,
    },
    {
      id: 'app-8',
      name: 'Washing Machine (Front Loader)',
      category: 'appliances',
      quantity: 1,
      watts: 900,
      hoursPerDay: 1.2,
      dayHours: 1.2,
      nightHours: 0,
      simultaneousFactor: 0.5,
      surgeMultiplier: 2.5,
      enabled: true,
    },
    {
      id: 'app-9',
      name: 'Microwave & Oven',
      category: 'kitchen',
      quantity: 1,
      watts: 1200,
      hoursPerDay: 0.6,
      dayHours: 0.4,
      nightHours: 0.2,
      simultaneousFactor: 0.4,
      surgeMultiplier: 1.5,
      enabled: true,
    },
    {
      id: 'app-10',
      name: 'Wi-Fi & CCTV System',
      category: 'electronics',
      quantity: 1,
      watts: 45,
      hoursPerDay: 24,
      dayHours: 12,
      nightHours: 12,
      simultaneousFactor: 1.0,
      surgeMultiplier: 1.0,
      enabled: true,
    },
    {
      id: 'app-11',
      name: 'Workstation & Laptops',
      category: 'electronics',
      quantity: 2,
      watts: 130,
      hoursPerDay: 8,
      dayHours: 6,
      nightHours: 2,
      simultaneousFactor: 0.8,
      surgeMultiplier: 1.1,
      enabled: true,
    },
  ],
  location: {
    country: 'Senegal',
    city: 'Thiès',
    peakSunHours: 5.5,
    cloudyDaysBuffer: 0,
  },
  solar: {
    panelWattage: 400,
    orientationEfficiency: 1.0,
    reserveMargin: 0.20, // +20% reserve
  },
  battery: {
    chemistry: 'LiFePO4',
    systemVoltage: 48,
    unitVoltage: 51.2,
    unitAh: 100,
    unitNominalKwh: 5.12,
    unitCost: 1450,
    dodLimit: 0.80,
    modelName: 'LiFePO4 51.2V 100Ah Server Rack',
    autonomyDays: 1.0,
  },
  inverter: {
    headroom: 0.25, // 25% headroom
    efficiency: 0.92,
  },
  mppt: {
    ratedCurrentA: 100,
    maxPvVoc: 450,
    mpptVmin: 120,
    mpptVmax: 430,
    maxInputCurrentA: 35,
    numberOfInputs: 2,
    unitCost: 650,
  },
  advanced: {
    systemLosses: 0.15,
    inverterEfficiency: 0.92,
    batteryRoundtripEfficiency: 0.92,
    pvDerating: 0.05,
    cableLoss: 0.02,
    tempDerating: 0.05,
    panelDegradationAnnual: 0.005,
    safeSocThreshold: 0.20,
    dangerSocThreshold: 0.10,
  },
  costs: {
    currency: 'USD',
    exchangeRateToUSD: 1.0,
    panelUnitPrice: 140,
    batteryUnitPrice: 1450,
    inverterUnitPrice: 2400,
    mpptUnitPrice: 650,
    mountingCost: 1200,
    dcProtectionCost: 550,
    acProtectionCost: 450,
    cablesCost: 600,
    installationCost: 2200,
    shippingCost: 800,
    customsCost: 650,
    miscCost: 350,
  },
  stringDesign: {
    panelVoc: 49.8,
    panelVmp: 41.5,
    panelIsc: 10.2,
    panelImp: 9.64,
    panelWatts: 400,
    tempMinC: 15,
    tempMaxC: 45,
    tempCoeffVoc: -0.28,
  },
};
